spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaee_2208_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ZMQaishiteru1229
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus: 
  global-config:
    db-config:
      table-prefix: t_
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml